plugins {
    id 'net.minecraftforge.licenser' version '1.2.0'
}

defaultTasks 'updateLicenses', 'shadowJar'

version '0.24.0'

subprojects {
    version = rootProject.version
    group = 'xyz.kyngs.librelogin'

    apply plugin: 'net.minecraftforge.licenser'

    repositories {
        mavenLocal()
        mavenCentral()

        maven {
            url 'https://jitpack.io'
        }
    }

    license {
        header = rootProject.file('HEADER.txt')
        include '**/*.java'
        newLine = true

        matching("**/protocollib/EncryptionUtil.java") {
            header = rootProject.file("licenses/FASTLOGIN_LICENSE")
        }
    }

}
